# -*- coding: utf-8 -*-
#公用配置
DEBUG = False
SQLALCHEMY_ECHO = False
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ENCODING = "utf8mb4"
SECRET_KEY = "123456imooc"
DEBUG_TB_INTERCEPT_REDIRECTS = False
AUTH_COOKIE_NAME = "movie_cat"
